namespace VgsTiledMap.Ags.VgsTile.Forms
{
    using ESRI.ArcGIS.Geometry;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class VgsTileDownloadForm : Form
    {
        private BackgroundWorker backgroundWorker;
        private Button btnBigImg;
        private Button btnDirSelect;
        private Button btnExit;
        private Button btnReset;
        private Button btnStart;
        private Button btnStartSelect;
        private ColumnHeader columnHeader1;
        private ColumnHeader columnHeader2;
        private ColumnHeader columnHeader3;
        private IContainer components;
        private FolderBrowserDialog folderDialog;
        private GroupBox gb_step1;
        private GroupBox gb_step2;
        private GroupBox groupBox3;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label lbl_Combine;
        private Label lblDownload;
        private Label lblInfo;
        private Label lblLT;
        private Label lblRB;
        private LinkLabel linkThreadSetting;
        private ListView lv;
        private NumericUpDown numThreadCount;
        private ProgressBar progressBar;
        private ProgressBar progressBar_Combine;
        private IPoint ptLowerRight;
        private IPoint ptUpperLeft;
        private string tilePath;
        private TextBox txtDir;
        private TextBox txtTaskName;

        public VgsTileDownloadForm()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.lblRB = new Label();
            this.lblLT = new Label();
            this.btnStartSelect = new Button();
            this.gb_step1 = new GroupBox();
            this.lv = new ListView();
            this.columnHeader1 = new ColumnHeader();
            this.columnHeader2 = new ColumnHeader();
            this.columnHeader3 = new ColumnHeader();
            this.txtTaskName = new TextBox();
            this.label1 = new Label();
            this.txtDir = new TextBox();
            this.label3 = new Label();
            this.gb_step2 = new GroupBox();
            this.numThreadCount = new NumericUpDown();
            this.btnDirSelect = new Button();
            this.linkThreadSetting = new LinkLabel();
            this.label2 = new Label();
            this.btnExit = new Button();
            this.btnReset = new Button();
            this.btnStart = new Button();
            this.progressBar_Combine = new ProgressBar();
            this.lbl_Combine = new Label();
            this.lblDownload = new Label();
            this.groupBox3 = new GroupBox();
            this.btnBigImg = new Button();
            this.lblInfo = new Label();
            this.progressBar = new ProgressBar();
            this.folderDialog = new FolderBrowserDialog();
            this.backgroundWorker = new BackgroundWorker();
            this.gb_step1.SuspendLayout();
            this.gb_step2.SuspendLayout();
            this.numThreadCount.BeginInit();
            this.groupBox3.SuspendLayout();
            base.SuspendLayout();
            this.lblRB.AutoSize = true;
            this.lblRB.Location = new System.Drawing.Point(0x11, 0x2a);
            this.lblRB.Name = "lblRB";
            this.lblRB.Size = new Size(0x29, 12);
            this.lblRB.TabIndex = 1;
            this.lblRB.Text = "右下：";
            this.lblLT.AutoSize = true;
            this.lblLT.Location = new System.Drawing.Point(0x11, 0x15);
            this.lblLT.Name = "lblLT";
            this.lblLT.Size = new Size(0x29, 12);
            this.lblLT.TabIndex = 1;
            this.lblLT.Text = "左上：";
            this.btnStartSelect.Location = new System.Drawing.Point(460, 0x15);
            this.btnStartSelect.Name = "btnStartSelect";
            this.btnStartSelect.Size = new Size(0x59, 30);
            this.btnStartSelect.TabIndex = 0;
            this.btnStartSelect.Text = "开始选择";
            this.btnStartSelect.UseVisualStyleBackColor = true;
            this.gb_step1.Controls.Add(this.lblRB);
            this.gb_step1.Controls.Add(this.lblLT);
            this.gb_step1.Controls.Add(this.btnStartSelect);
            this.gb_step1.Location = new System.Drawing.Point(12, 12);
            this.gb_step1.Name = "gb_step1";
            this.gb_step1.Size = new Size(0x22e, 0x43);
            this.gb_step1.TabIndex = 1;
            this.gb_step1.TabStop = false;
            this.gb_step1.Text = "1 选择地图范围";
            this.lv.Columns.AddRange(new ColumnHeader[] { this.columnHeader1, this.columnHeader2, this.columnHeader3 });
            this.lv.FullRowSelect = true;
            this.lv.HideSelection = false;
            this.lv.Location = new System.Drawing.Point(3, 0x13);
            this.lv.Name = "lv";
            this.lv.Size = new Size(0xf4, 110);
            this.lv.TabIndex = 0x13;
            this.lv.UseCompatibleStateImageBehavior = false;
            this.lv.View = View.Details;
            this.columnHeader1.Text = "级别";
            this.columnHeader1.Width = 50;
            this.columnHeader2.Text = "瓦片数";
            this.columnHeader2.Width = 0x5f;
            this.columnHeader3.Text = "预计大小";
            this.columnHeader3.Width = 0x5e;
            this.txtTaskName.Location = new System.Drawing.Point(0x153, 60);
            this.txtTaskName.Name = "txtTaskName";
            this.txtTaskName.Size = new Size(0xa7, 0x15);
            this.txtTaskName.TabIndex = 3;
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(0x10b, 0x40);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x35, 12);
            this.label1.TabIndex = 1;
            this.label1.Text = "任务名称";
            this.txtDir.Location = new System.Drawing.Point(0x153, 100);
            this.txtDir.Name = "txtDir";
            this.txtDir.ReadOnly = true;
            this.txtDir.Size = new Size(0xa7, 0x15);
            this.txtDir.TabIndex = 3;
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(0x10b, 0x68);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x41, 12);
            this.label3.TabIndex = 1;
            this.label3.Text = "存放文件夹";
            this.gb_step2.Controls.Add(this.lv);
            this.gb_step2.Controls.Add(this.numThreadCount);
            this.gb_step2.Controls.Add(this.btnDirSelect);
            this.gb_step2.Controls.Add(this.linkThreadSetting);
            this.gb_step2.Controls.Add(this.txtTaskName);
            this.gb_step2.Controls.Add(this.label1);
            this.gb_step2.Controls.Add(this.txtDir);
            this.gb_step2.Controls.Add(this.label3);
            this.gb_step2.Controls.Add(this.label2);
            this.gb_step2.Location = new System.Drawing.Point(12, 0x55);
            this.gb_step2.Name = "gb_step2";
            this.gb_step2.Size = new Size(0x22e, 0x87);
            this.gb_step2.TabIndex = 2;
            this.gb_step2.TabStop = false;
            this.gb_step2.Text = "2 设置下载属性";
            this.numThreadCount.Location = new System.Drawing.Point(0x148, 0x13);
            this.numThreadCount.Name = "numThreadCount";
            this.numThreadCount.Size = new Size(50, 0x15);
            this.numThreadCount.TabIndex = 0x12;
            this.btnDirSelect.Location = new System.Drawing.Point(0x200, 0x63);
            this.btnDirSelect.Name = "btnDirSelect";
            this.btnDirSelect.Size = new Size(0x25, 0x17);
            this.btnDirSelect.TabIndex = 4;
            this.btnDirSelect.Text = "选择";
            this.btnDirSelect.UseVisualStyleBackColor = true;
            this.linkThreadSetting.AutoSize = true;
            this.linkThreadSetting.Location = new System.Drawing.Point(0x180, 0x17);
            this.linkThreadSetting.Name = "linkThreadSetting";
            this.linkThreadSetting.Size = new Size(0x4d, 12);
            this.linkThreadSetting.TabIndex = 0x11;
            this.linkThreadSetting.TabStop = true;
            this.linkThreadSetting.Text = "点击设置线程";
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(0x10b, 0x17);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x41, 12);
            this.label2.TabIndex = 1;
            this.label2.Text = "线程设置：";
//            this.btnExit.DialogResult = DialogResult.Cancel;
            this.btnExit.Location = new System.Drawing.Point(0x1df, 0xe2);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new Size(0x5b, 0x17);
            this.btnExit.TabIndex = 5;
            this.btnExit.Text = "退 出";
            this.btnExit.UseVisualStyleBackColor = true;
            this.btnReset.Location = new System.Drawing.Point(0x16f, 0xe2);
            this.btnReset.Name = "btnReset";
            this.btnReset.Size = new Size(0x6a, 0x17);
            this.btnReset.TabIndex = 4;
            this.btnReset.Text = "重置参数";
            this.btnReset.UseVisualStyleBackColor = true;
            this.btnStart.Location = new System.Drawing.Point(12, 0xe2);
            this.btnStart.Name = "btnStart";
            this.btnStart.Size = new Size(0x12f, 0x17);
            this.btnStart.TabIndex = 3;
            this.btnStart.Text = "开始下载";
            this.btnStart.UseVisualStyleBackColor = false;
            this.progressBar_Combine.Location = new System.Drawing.Point(60, 0x6d);
            this.progressBar_Combine.Name = "progressBar_Combine";
            this.progressBar_Combine.Size = new Size(490, 0x21);
            this.progressBar_Combine.Step = 1;
            this.progressBar_Combine.TabIndex = 7;
            this.progressBar_Combine.Visible = false;
            this.lbl_Combine.AutoSize = true;
            this.lbl_Combine.Location = new System.Drawing.Point(3, 0x79);
            this.lbl_Combine.Name = "lbl_Combine";
            this.lbl_Combine.Size = new Size(0x35, 12);
            this.lbl_Combine.TabIndex = 5;
            this.lbl_Combine.Text = "合成进度";
            this.lbl_Combine.Visible = false;
            this.lblDownload.AutoSize = true;
            this.lblDownload.Location = new System.Drawing.Point(6, 0x25);
            this.lblDownload.Name = "lblDownload";
            this.lblDownload.Size = new Size(0x35, 12);
            this.lblDownload.TabIndex = 6;
            this.lblDownload.Text = "下载进度";
            this.groupBox3.Controls.Add(this.btnBigImg);
            this.groupBox3.Controls.Add(this.progressBar_Combine);
            this.groupBox3.Controls.Add(this.lbl_Combine);
            this.groupBox3.Controls.Add(this.lblInfo);
            this.groupBox3.Controls.Add(this.progressBar);
            this.groupBox3.Controls.Add(this.lblDownload);
            this.groupBox3.Location = new System.Drawing.Point(11, 0xff);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(0x22f, 0x9d);
            this.groupBox3.TabIndex = 6;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "状态监控";
            this.btnBigImg.Anchor = AnchorStyles.Left | AnchorStyles.Bottom;
            this.btnBigImg.Font = new Font("SimSun", 9f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            this.btnBigImg.ForeColor = Color.Red;
            this.btnBigImg.Location = new System.Drawing.Point(0x1cf, 0x4c);
            this.btnBigImg.Name = "btnBigImg";
            this.btnBigImg.Size = new Size(0x57, 0x1d);
            this.btnBigImg.TabIndex = 13;
            this.btnBigImg.Text = "瓦片拼接";
            this.btnBigImg.UseVisualStyleBackColor = true;
            this.btnBigImg.Visible = false;
            this.lblInfo.AutoSize = true;
            this.lblInfo.BackColor = Color.Transparent;
            this.lblInfo.Location = new System.Drawing.Point(0x3a, 0x57);
            this.lblInfo.Name = "lblInfo";
            this.lblInfo.Size = new Size(0x4d, 12);
            this.lblInfo.TabIndex = 9;
            this.lblInfo.Text = "下载状态信息";
            this.progressBar.Location = new System.Drawing.Point(60, 20);
            this.progressBar.Name = "progressBar";
            this.progressBar.Size = new Size(490, 50);
            this.progressBar.Step = 1;
            this.progressBar.TabIndex = 8;
            base.AutoScaleDimensions = new SizeF(6f, 12f);
//            base.AutoScaleMode = AutoScaleMode.Font;
            base.ClientSize = new Size(0x24c, 0x1ab);
            base.Controls.Add(this.groupBox3);
            base.Controls.Add(this.btnExit);
            base.Controls.Add(this.btnReset);
            base.Controls.Add(this.btnStart);
            base.Controls.Add(this.gb_step2);
            base.Controls.Add(this.gb_step1);
//            base.FormBorderStyle = FormBorderStyle.FixedToolWindow;
            base.Name = "VgsTileDownloadForm";
            base.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "地图瓦片数据下载";
            this.gb_step1.ResumeLayout(false);
            this.gb_step1.PerformLayout();
            this.gb_step2.ResumeLayout(false);
            this.gb_step2.PerformLayout();
            this.numThreadCount.EndInit();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            base.ResumeLayout(false);
        }
    }
}

