namespace GISControlsClass
{
    using DevExpress.XtraTreeList;
    using DevExpress.XtraTreeList.Columns;
    using FormBase;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class UserControlSelectFeatureReport : UserControlBase1
    {
        private ColumnHeader columnHeader1;
        private ColumnHeader columnHeader2;
        private ColumnHeader columnHeader3;
        private IContainer components;
        private ImageList imageList1;
        private ImageList imageList2;
        private ListView listView1;
        private TreeList treeList1;
        private TreeListColumn treeListColumn1;
        private TreeListColumn treeListColumn2;
        private TreeListColumn treeListColumn3;

        public UserControlSelectFeatureReport()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new Container();
            ListViewGroup group = new ListViewGroup("ListViewGroup", HorizontalAlignment.Left);
            ListViewGroup group2 = new ListViewGroup("ListViewGroup", HorizontalAlignment.Left);
            ListViewItem item = new ListViewItem(new string[] { "1", "11", "12" }, -1);
            ListViewItem item2 = new ListViewItem(new string[] { "2", "21", "22" }, -1);
            ComponentResourceManager resources = new ComponentResourceManager(typeof(UserControlSelectFeatureReport));
            this.listView1 = new ListView();
            this.columnHeader1 = new ColumnHeader();
            this.columnHeader2 = new ColumnHeader();
            this.columnHeader3 = new ColumnHeader();
            this.treeList1 = new TreeList();
            this.treeListColumn1 = new TreeListColumn();
            this.treeListColumn2 = new TreeListColumn();
            this.treeListColumn3 = new TreeListColumn();
            this.imageList1 = new ImageList(this.components);
            this.imageList2 = new ImageList(this.components);
            this.treeList1.BeginInit();
            base.SuspendLayout();
//            this.listView1.BorderStyle = BorderStyle.None;
            this.listView1.Columns.AddRange(new ColumnHeader[] { this.columnHeader1, this.columnHeader2, this.columnHeader3 });
            this.listView1.Dock = DockStyle.Top;
            group.Header = "ListViewGroup";
            group.Name = "listViewGroup1";
            group2.Header = "ListViewGroup";
            group2.Name = "listViewGroup2";
            this.listView1.Groups.AddRange(new ListViewGroup[] { group, group2 });
            this.listView1.Items.AddRange(new ListViewItem[] { item, item2 });
            this.listView1.Location = new Point(2, 2);
            this.listView1.Name = "listView1";
            this.listView1.Size = new Size(0x16a, 0x59);
            this.listView1.TabIndex = 0;
            this.listView1.UseCompatibleStateImageBehavior = false;
            this.listView1.View = View.Details;
            this.listView1.Visible = false;
            this.columnHeader1.Text = "Header";
            this.columnHeader1.Width = 0x81;
            this.columnHeader2.Text = "Header2";
            this.columnHeader2.Width = 0x66;
            this.columnHeader3.Text = "Header3";
            this.columnHeader3.Width = 100;
            this.treeList1.Columns.AddRange(new TreeListColumn[] { this.treeListColumn1, this.treeListColumn2, this.treeListColumn3 });
            this.treeList1.Dock = DockStyle.Fill;
            this.treeList1.Location = new Point(2, 0x5b);
            this.treeList1.Name = "treeList1";
            this.treeList1.BeginUnboundLoad();
            this.treeList1.AppendNode(new object[] { "小班", "", "" }, -1, -1, -1, 110);
            this.treeList1.AppendNode(new object[] { "OID1", "XX村", "纯林" }, 0, -1, -1, 0);
            object[] nodeData = new object[3];
            nodeData[0] = "林班";
            this.treeList1.AppendNode(nodeData, -1, 0, 0, 110);
            this.treeList1.EndUnboundLoad();
            this.treeList1.OptionsBehavior.Editable = false;
            this.treeList1.OptionsView.ShowHorzLines = false;
            this.treeList1.OptionsView.ShowIndicator = false;
            this.treeList1.OptionsView.ShowRoot = false;
            this.treeList1.OptionsView.ShowRowFooterSummary = true;
            this.treeList1.OptionsView.ShowSummaryFooter = true;
            this.treeList1.SelectImageList = this.imageList1;
            this.treeList1.Size = new Size(0x16a, 320);
            this.treeList1.StateImageList = this.imageList1;
            this.treeList1.TabIndex = 1;
            this.treeListColumn1.Caption = "名";
            this.treeListColumn1.FieldName = "treeListColumn1";
            this.treeListColumn1.MinWidth = 0x47;
            this.treeListColumn1.Name = "treeListColumn1";
            this.treeListColumn1.Visible = true;
            this.treeListColumn1.VisibleIndex = 0;
            this.treeListColumn1.Width = 0x7a;
            this.treeListColumn2.Caption = "值";
            this.treeListColumn2.FieldName = "值";
            this.treeListColumn2.Name = "treeListColumn2";
            this.treeListColumn2.Visible = true;
            this.treeListColumn2.VisibleIndex = 1;
            this.treeListColumn2.Width = 100;
            this.treeListColumn3.Caption = "值2";
            this.treeListColumn3.FieldName = "值2";
            this.treeListColumn3.Name = "treeListColumn3";
            this.treeListColumn3.Visible = true;
            this.treeListColumn3.VisibleIndex = 2;
            this.treeListColumn3.Width = 0x7b;
            this.imageList1.ImageStream = (ImageListStreamer) resources.GetObject("imageList1.ImageStream");
            this.imageList1.TransparentColor = Color.Transparent;
            this.imageList1.Images.SetKeyName(0, "(01,48).png");
            this.imageList1.Images.SetKeyName(1, "(08,01).png");
            this.imageList1.Images.SetKeyName(2, "(02,26).png");
            this.imageList1.Images.SetKeyName(3, "(17,02).png");
            this.imageList1.Images.SetKeyName(4, "(03,02).png");
            this.imageList1.Images.SetKeyName(5, "(03,11).png");
            this.imageList1.Images.SetKeyName(6, "(03,43).png");
            this.imageList1.Images.SetKeyName(7, "(04,43).png");
            this.imageList1.Images.SetKeyName(8, "(06,00).png");
            this.imageList1.Images.SetKeyName(9, "(06,08).png");
            this.imageList1.Images.SetKeyName(10, "(14,26).png");
            this.imageList1.Images.SetKeyName(11, "(25,02).png");
            this.imageList1.Images.SetKeyName(12, "(05,32).png");
            this.imageList1.Images.SetKeyName(13, "(08,32).png");
            this.imageList1.Images.SetKeyName(14, "(13,32).png");
            this.imageList1.Images.SetKeyName(15, "(11,32).png");
            this.imageList1.Images.SetKeyName(0x10, "(14,32).png");
            this.imageList1.Images.SetKeyName(0x11, "(07,13).png");
            this.imageList1.Images.SetKeyName(0x12, "(08,40).png");
            this.imageList1.Images.SetKeyName(0x13, "(11,14).png");
            this.imageList1.Images.SetKeyName(20, "(03,34).png");
            this.imageList1.Images.SetKeyName(0x15, "(09,13).png");
            this.imageList1.Images.SetKeyName(0x16, "(09,21).png");
            this.imageList1.Images.SetKeyName(0x17, "(12,43).png");
            this.imageList1.Images.SetKeyName(0x18, "(13,11).png");
            this.imageList1.Images.SetKeyName(0x19, "(15,02).png");
            this.imageList1.Images.SetKeyName(0x1a, "(16,32).png");
            this.imageList1.Images.SetKeyName(0x1b, "(17,49).png");
            this.imageList1.Images.SetKeyName(0x1c, "(18,01).png");
            this.imageList1.Images.SetKeyName(0x1d, "(06,09).png");
            this.imageList1.Images.SetKeyName(30, "(18,39).png");
            this.imageList1.Images.SetKeyName(0x1f, "(19,01).png");
            this.imageList1.Images.SetKeyName(0x20, "(20,24).png");
            this.imageList1.Images.SetKeyName(0x21, "(21,36).png");
            this.imageList1.Images.SetKeyName(0x22, "(22,04).png");
            this.imageList1.Images.SetKeyName(0x23, "(24,41).png");
            this.imageList1.Images.SetKeyName(0x24, "(24,44).png");
            this.imageList1.Images.SetKeyName(0x25, "(26,42).png");
            this.imageList1.Images.SetKeyName(0x26, "(27,07).png");
            this.imageList1.Images.SetKeyName(0x27, "(27,15).png");
            this.imageList1.Images.SetKeyName(40, "(29,04).png");
            this.imageList1.Images.SetKeyName(0x29, "(29,34).png");
            this.imageList1.Images.SetKeyName(0x2a, "(30,14).png");
            this.imageList1.Images.SetKeyName(0x2b, "(31,35).png");
            this.imageList1.Images.SetKeyName(0x2c, "(32,04).png");
            this.imageList1.Images.SetKeyName(0x2d, "(33,08).png");
            this.imageList1.Images.SetKeyName(0x2e, "(33,14).png");
            this.imageList1.Images.SetKeyName(0x2f, "(33,16).png");
            this.imageList1.Images.SetKeyName(0x30, "(35,29).png");
            this.imageList1.Images.SetKeyName(0x31, "(37,29).png");
            this.imageList1.Images.SetKeyName(50, "(37,41).png");
            this.imageList1.Images.SetKeyName(0x33, "(39,04).png");
            this.imageList1.Images.SetKeyName(0x34, "(39,05).png");
            this.imageList1.Images.SetKeyName(0x35, "(39,47).png");
            this.imageList1.Images.SetKeyName(0x36, "(40,05).png");
            this.imageList1.Images.SetKeyName(0x37, "(48,36).png");
            this.imageList1.Images.SetKeyName(0x38, "(49,48).png");
            this.imageList1.Images.SetKeyName(0x39, "(00,49).png");
            this.imageList1.Images.SetKeyName(0x3a, "9.png");
            this.imageList1.Images.SetKeyName(0x3b, "10.png");
            this.imageList1.Images.SetKeyName(60, "11.png");
            this.imageList1.Images.SetKeyName(0x3d, "(60).gif");
            this.imageList1.Images.SetKeyName(0x3e, "(62).gif");
            this.imageList1.Images.SetKeyName(0x3f, "(65).gif");
            this.imageList1.Images.SetKeyName(0x40, "(66).gif");
            this.imageList1.Images.SetKeyName(0x41, "(71).gif");
            this.imageList1.Images.SetKeyName(0x42, "(73).gif");
            this.imageList1.Images.SetKeyName(0x43, "(74).gif");
            this.imageList1.Images.SetKeyName(0x44, "(103).gif");
            this.imageList1.Images.SetKeyName(0x45, "(104).gif");
            this.imageList1.Images.SetKeyName(70, "(135).gif");
            this.imageList1.Images.SetKeyName(0x47, "(138).gif");
            this.imageList1.Images.SetKeyName(0x48, "(181).gif");
            this.imageList1.Images.SetKeyName(0x49, "(315).gif");
            this.imageList1.Images.SetKeyName(0x4a, "(318).gif");
            this.imageList1.Images.SetKeyName(0x4b, "(319).gif");
            this.imageList1.Images.SetKeyName(0x4c, "(322).gif");
            this.imageList1.Images.SetKeyName(0x4d, "(323).gif");
            this.imageList1.Images.SetKeyName(0x4e, "(331).gif");
            this.imageList1.Images.SetKeyName(0x4f, "(336).gif");
            this.imageList1.Images.SetKeyName(80, "(463).gif");
            this.imageList1.Images.SetKeyName(0x51, "(823).gif");
            this.imageList1.Images.SetKeyName(0x52, "(829).gif");
            this.imageList1.Images.SetKeyName(0x53, "(834).gif");
            this.imageList1.Images.SetKeyName(0x54, "(835).gif");
            this.imageList1.Images.SetKeyName(0x55, "(836).gif");
            this.imageList1.Images.SetKeyName(0x56, "(905).gif");
            this.imageList1.Images.SetKeyName(0x57, "(915).gif");
            this.imageList1.Images.SetKeyName(0x58, "(944).gif");
            this.imageList1.Images.SetKeyName(0x59, "(945).gif");
            this.imageList1.Images.SetKeyName(90, "(1074).gif");
            this.imageList1.Images.SetKeyName(0x5b, "(1202).gif");
            this.imageList1.Images.SetKeyName(0x5c, "(1277).gif");
            this.imageList1.Images.SetKeyName(0x5d, "(1443).gif");
            this.imageList1.Images.SetKeyName(0x5e, "(1448).gif");
            this.imageList1.Images.SetKeyName(0x5f, "(1460).gif");
            this.imageList1.Images.SetKeyName(0x60, "(1467).gif");
            this.imageList1.Images.SetKeyName(0x61, "(1755).gif");
            this.imageList1.Images.SetKeyName(0x62, "closed_polyline.png");
            this.imageList1.Images.SetKeyName(0x63, "layer-shape-line.png");
            this.imageList1.Images.SetKeyName(100, "layer-select-point.png");
            this.imageList1.Images.SetKeyName(0x65, "layer-shape-curve.png");
            this.imageList1.Images.SetKeyName(0x66, "1259566014_stock_draw-polygon.ico");
            this.imageList1.Images.SetKeyName(0x67, "map.png");
            this.imageList1.Images.SetKeyName(0x68, "map_edit2.png");
            this.imageList1.Images.SetKeyName(0x69, "map2.png");
            this.imageList1.Images.SetKeyName(0x6a, "map--pencil.png");
            this.imageList1.Images.SetKeyName(0x6b, "maps.png");
            this.imageList1.Images.SetKeyName(0x6c, "maps-stack.png");
            this.imageList1.Images.SetKeyName(0x6d, "ksirtet16.png");
            this.imageList1.Images.SetKeyName(110, "stock_draw-polygon-filled-16.png");
            this.imageList2.ColorDepth = ColorDepth.Depth24Bit;
            this.imageList2.ImageSize = new Size(0x10, 0x10);
            this.imageList2.TransparentColor = Color.Transparent;
            base.Appearance.BackColor = Color.FromArgb(0xe3, 0xf1, 0xfe);
            base.Appearance.BackColor2 = Color.FromArgb(0xe3, 0xf1, 0xfe);
            base.Appearance.Options.UseBackColor = true;
            base.AutoScaleDimensions = new SizeF(7f, 14f);
//            base.AutoScaleMode = AutoScaleMode.Font;
            base.Controls.Add(this.treeList1);
            base.Controls.Add(this.listView1);
            base.Name = "UserControlSelectFeatureReport";
            base.Padding = new Padding(2);
            base.Size = new Size(0x16e, 0x19d);
            this.treeList1.EndInit();
            base.ResumeLayout(false);
        }
    }
}

